#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Return to the root directory (this will be the root of your Git repo)
cd "$(git rev-parse --show-toplevel)"

# Your commands
dotnet restore
dotnet tool restore
dotnet build --configuration Release --no-restore
dotnet format --verify-no-changes
dotnet test --configuration Release --no-restore --no-build --framework net9.0 --verbosity normal
dotnet pack --configuration Release --no-restore --no-build
